openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate Swagger integration with Flask.
  version: 1.0.0
paths:
  /api/hello:
    get:
      summary: Returns a greeting message.
      responses:
        200:
          description: A greeting message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
  /api/data:
    post:
      summary: Echoes the posted data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: The echoed data.
          content:
            application/json:
              schema:
                type: object
