openapi: 3.0.3
info:
  title: Vehiculos Oficiales
  description: |-
    Se dispone de una api que permite realizar funciones de gestion de vehiculos oficiales con el siguiente modelo de datos (roles, usuarios,vehiculos y tarjetones). 
    También se va a realizar el uso de la blockchain con la funcion registrarTarjeton(). Los tarjetones son los permisos que llevan los vehiculos oficiales para permitirles estacionar en cualquier lugar disponible 
    y son utilizados por personal policial para verificar su validez en caso de ser necesario.  El contrato estará formado por los siguientes datos (idVehiculo,dominio,fechaRegistro,añoValidez) y sera alojado en la red (Sepolia).
    
    Acceso al repositorio en:[https://github.com/empresarial789/sistemasdistribuidos](https://github.com/empresarial789/sistemasdistribuidos)

  version: 1.0.0
servers:
  - url: https://localhost:5000/index.html
paths:
  /v1/vehiculos/registrarTarjeton:
    get:
      tags:
        - pet
      summary: Registra un tarjeton fake
      description: Prueba de llamado para registrar valores fake en un tarjeton de la blockchain de Sepolia.
      operationId: registrarTarjeton
      responses:
        '200':
          description: operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta'    
        '406':
          description: tipo de contenido de la solicitud invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
  /v1/usuarios/registrar:
    post:
      tags:
        - user
      summary: Registro de usuario
      description: Registro de usuario.
      operationId: createUser
      parameters:
        - name: usuario
          in: query
          description: El nombre del usuario
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: El password para el login
          required: false
          schema:
            type: string
      responses:
        '201':
          description: operacion exitosa.los headers indicados a futuro se devolveran en produccion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuestaRegister' 
        '400':
          description: Invalido username o password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
  /v1/usuarios/login:
    get:
      tags:
        - user
      summary: Login de usuario al systema
      description: ''
      operationId: loginUser
      parameters:
        - name: usuario
          in: query
          description: El nombre del usuario
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: El password para el login
          required: false
          schema:
            type: string
      responses:
        '200':
          description: operacion exitosa.los headers indicados a futuro se devolveran en produccion
          headers:
            X-Rate-Limit:
              description: llamadas por hora permitidas por un usuario
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: fecha en UTC cuando expira el token
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
        '400':
          description: Invalido username o password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
        '401':
          description: Usuario no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
        '415':
          description: Tipo de content type de solicitud invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
        '500':
          description: error generico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRespuesta' 
 
components:
  schemas:
    ApiRespuesta:
      type: object
      properties:
        message:
          type: string
          description: mensaje
          example: mensaje ok
      xml:
        name: apiRespuesta
    ApiRespuestaRegister:
      type: object
      properties:
        message:
          type: string
          description: mensaje
          example: mensaje ok
        api_key:
          type: string
          description: retorna la api key
          example: 2151515464613236646446d5fsdgdsf
      xml:
        name: apiRespuesta